[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
	cache-control = '''
	max-age=604800,
	no-cache,
	no-store,
	must-revalidate'''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

  [build]
  publish = "dist"

# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
